openapi: 3.0.3
info:
  title: x402 Facilitator API
  description: API specification for x402 payment facilitator services
  version: 1.0.0
servers:
  - url: https://facilitator.example.com
    description: Primary facilitator endpoint
  - url: https://fallback.facilitator.example.com
    description: Fallback facilitator endpoint

paths:
  /verify:
    post:
      summary: Verify payment authorization
      description: Validates a payment authorization without executing blockchain transaction
      operationId: verifyPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacilitatorRequest'
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /settle:
    post:
      summary: Settle payment on blockchain
      description: Executes a verified payment by broadcasting to blockchain
      operationId: settlePayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacilitatorRequest'
      responses:
        '200':
          description: Settlement result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettlementResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /supported:
    get:
      summary: Get supported payment types
      description: Returns list of supported schemes and networks
      operationId: getSupportedPayments
      responses:
        '200':
          description: Supported payment types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportedResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    FacilitatorRequest:
      type: object
      required:
        - paymentPayload
        - paymentRequirements
      properties:
        paymentPayload:
          $ref: '#/components/schemas/PaymentPayload'
        paymentRequirements:
          $ref: '#/components/schemas/PaymentRequirement'

    PaymentPayload:
      type: object
      required:
        - x402Version
        - scheme
        - network
        - payload
      properties:
        x402Version:
          type: integer
          example: 1
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "base-sepolia"
        payload:
          oneOf:
            - $ref: '#/components/schemas/EVMPayload'
            - $ref: '#/components/schemas/SVMPayload'

    EVMPayload:
      type: object
      required:
        - signature
        - authorization
      properties:
        signature:
          type: string
          pattern: '^0x[a-fA-F0-9]+$'
          example: "0x2d6a7588d6acca505cbf0d9a4a227e0c52c6c34008c8e8986a1283259764173608a2ce6496642e377d6da8dbbf5836e9bd15092f9ecab05ded3d6293af148b571c"
        authorization:
          type: object
          required:
            - from
            - to
            - value
            - validAfter
            - validBefore
            - nonce
          properties:
            from:
              type: string
              pattern: '^0x[a-fA-F0-9]{40}$'
              example: "0x857b06519E91e3A54538791bDbb0E22373e36b66"
            to:
              type: string
              pattern: '^0x[a-fA-F0-9]{40}$'
              example: "0x209693Bc6afc0C5328bA36FaF03C514EF312287C"
            value:
              type: string
              example: "10000"
            validAfter:
              type: string
              example: "1740672089"
            validBefore:
              type: string
              example: "1740672154"
            nonce:
              type: string
              pattern: '^0x[a-fA-F0-9]{64}$'
              example: "0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f13480"

    SVMPayload:
      type: object
      required:
        - transaction
      properties:
        transaction:
          type: string
          format: byte
          description: Base64-encoded serialized Solana transaction

    PaymentRequirement:
      type: object
      required:
        - scheme
        - network
        - maxAmountRequired
        - asset
        - payTo
        - resource
        - description
        - maxTimeoutSeconds
      properties:
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "base-sepolia"
        maxAmountRequired:
          type: string
          example: "10000"
        asset:
          type: string
          example: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
        payTo:
          type: string
          example: "0x209693Bc6afc0C5328bA36FaF03C514EF312287C"
        resource:
          type: string
          format: uri
          example: "https://api.example.com/premium-data"
        description:
          type: string
          example: "Access to premium market data"
        mimeType:
          type: string
          example: "application/json"
        outputSchema:
          type: object
        maxTimeoutSeconds:
          type: integer
          example: 60
        extra:
          type: object
          additionalProperties: true

    VerifyResponse:
      type: object
      required:
        - isValid
        - payer
      properties:
        isValid:
          type: boolean
        invalidReason:
          type: string
          enum:
            - insufficient_funds
            - invalid_signature
            - invalid_authorization
            - expired_authorization
            - invalid_nonce
            - recipient_mismatch
        payer:
          type: string
          example: "0x857b06519E91e3A54538791bDbb0E22373e36b66"

    SettlementResponse:
      type: object
      required:
        - success
        - transaction
        - network
        - payer
      properties:
        success:
          type: boolean
        errorReason:
          type: string
        transaction:
          type: string
          example: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
        network:
          type: string
          example: "base-sepolia"
        payer:
          type: string
          example: "0x857b06519E91e3A54538791bDbb0E22373e36b66"

    SupportedResponse:
      type: object
      required:
        - kinds
      properties:
        kinds:
          type: array
          items:
            type: object
            required:
              - x402Version
              - scheme
              - network
            properties:
              x402Version:
                type: integer
                example: 1
              scheme:
                type: string
                example: "exact"
              network:
                type: string
                example: "base-sepolia"
              extra:
                type: object
                additionalProperties: true
                description: Network-specific metadata (e.g., feePayer for SVM chains)
                example:
                  feePayer: "C7ckEzH4varMpBQsaD9bJZSCnWVyk4zAKYA85spuuNbR"

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code for programmatic handling