openapi: 3.0.0
info:
  title: MCP x402 Payment Integration API
  version: 1.0.0
  description: API specification for x402 payment flows in MCP (Model Context Protocol)

paths:
  /mcp:
    post:
      summary: MCP JSON-RPC Endpoint
      description: Handles all MCP protocol communications with x402 payment support
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JSONRPCRequest'
      responses:
        '200':
          description: Successful response or JSON-RPC error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/JSONRPCResponse'
                  - $ref: '#/components/schemas/JSONRPCError402'
            text/event-stream:
              schema:
                type: string
                description: Server-sent events stream for bidirectional communication

components:
  schemas:
    JSONRPCRequest:
      type: object
      required:
        - jsonrpc
        - method
        - id
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        method:
          type: string
          example: "tools/call"
        params:
          $ref: '#/components/schemas/ToolCallParams'
        id:
          oneOf:
            - type: string
            - type: number

    ToolCallParams:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the MCP tool to invoke
        arguments:
          type: object
          description: Tool-specific arguments
        _meta:
          type: object
          properties:
            x402/payment:
              $ref: '#/components/schemas/PaymentPayload'

    JSONRPCResponse:
      type: object
      required:
        - jsonrpc
        - id
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        result:
          $ref: '#/components/schemas/ToolCallResult'
        error:
          $ref: '#/components/schemas/JSONRPCErrorDetails'
        id:
          oneOf:
            - type: string
            - type: number

    ToolCallResult:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/MCPContent'
        _meta:
          type: object
          properties:
            x402/payment-response:
              $ref: '#/components/schemas/SettlementResponse'

    MCPContent:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum: ["text", "image", "resource"]
        text:
          type: string
        data:
          type: string
        mimeType:
          type: string

    JSONRPCError402:
      type: object
      required:
        - jsonrpc
        - error
        - id
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        error:
          type: object
          required:
            - code
            - message
            - data
          properties:
            code:
              type: integer
              enum: [402]
            message:
              type: string
              example: "Payment required"
            data:
              $ref: '#/components/schemas/PaymentRequirements'
        id:
          oneOf:
            - type: string
            - type: number

    JSONRPCErrorDetails:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object

    PaymentRequirements:
      type: object
      required:
        - x402Version
        - error
        - accepts
      properties:
        x402Version:
          type: integer
          enum: [1]
        error:
          type: string
          example: "Payment required to access this resource"
        accepts:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/PaymentRequirement'

    PaymentRequirement:
      type: object
      required:
        - scheme
        - network
        - maxAmountRequired
        - asset
        - payTo
        - resource
        - maxTimeoutSeconds
      properties:
        scheme:
          type: string
          enum: ["exact"]
        network:
          type: string
          example: "base"
        maxAmountRequired:
          type: string
          description: Amount in atomic units (wei, lamports)
          example: "10000"
        asset:
          type: string
          description: Token contract or mint address
          example: "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
        payTo:
          type: string
          description: Recipient wallet address
        resource:
          type: string
          example: "mcp://tools/search"
        description:
          type: string
        mimeType:
          type: string
          default: "application/json"
        maxTimeoutSeconds:
          type: integer
          default: 60
        extra:
          type: object
          additionalProperties:
            type: string

    PaymentPayload:
      type: object
      required:
        - x402Version
        - scheme
        - network
        - payload
      properties:
        x402Version:
          type: integer
          enum: [1]
        scheme:
          type: string
          enum: ["exact"]
        network:
          type: string
        payload:
          oneOf:
            - $ref: '#/components/schemas/EVMPayload'
            - $ref: '#/components/schemas/SVMPayload'

    EVMPayload:
      type: object
      required:
        - signature
        - authorization
      properties:
        signature:
          type: string
          pattern: '^0x[a-fA-F0-9]+$'
        authorization:
          type: object
          required:
            - from
            - to
            - value
            - validAfter
            - validBefore
            - nonce
          properties:
            from:
              type: string
              pattern: '^0x[a-fA-F0-9]{40}$'
            to:
              type: string
              pattern: '^0x[a-fA-F0-9]{40}$'
            value:
              type: string
            validAfter:
              type: string
            validBefore:
              type: string
            nonce:
              type: string
              pattern: '^0x[a-fA-F0-9]{64}$'

    SVMPayload:
      type: object
      required:
        - transaction
      properties:
        transaction:
          type: string
          description: Base64-encoded partially signed Solana transaction

    SettlementResponse:
      type: object
      required:
        - success
        - network
        - payer
      properties:
        success:
          type: boolean
        transaction:
          type: string
          description: Blockchain transaction hash
        network:
          type: string
        payer:
          type: string
          description: Address that made the payment
        errorReason:
          type: string